// <auto-generated />
using System;
using LicenseMe.Cache.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseMe.Cache.Migrations
{
    [DbContext(typeof(LicenseDbContext))]
    [Migration("20260702072040_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OpenSourceInitiative.LicenseApi.Models.OsiLicense", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("approval_date");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("approved");

                    b.Property<string>("BoardMinutes")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("board_minutes");

                    b.PrimitiveCollection<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("keywords");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LicenseStewardUrl")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("license_steward_url");

                    b.Property<string>("LicenseStewardVersion")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("license_steward_version");

                    b.Property<string>("LicenseText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("SpdxId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("spdx_id");

                    b.PrimitiveCollection<string>("Stewards")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("stewards");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("submission_date");

                    b.Property<string>("SubmissionUrl")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("submission_url");

                    b.Property<string>("SubmitterName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("submitter_name");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("OsiLicense", (string)null);

                    b.SplitToTable("LicenseText", null, t =>
                        {
                            t.Property("LicenseText");
                        });

                    b.SplitToTable("OsiLicenseTimestamp", null, t =>
                        {
                            t.Property("LastUpdatedUtc")
                                .HasColumnName("Timestamp");
                        });
                });

            modelBuilder.Entity("OpenSourceInitiative.LicenseApi.Models.OsiLicense", b =>
                {
                    b.HasOne("OpenSourceInitiative.LicenseApi.Models.OsiLicense", null)
                        .WithOne()
                        .HasForeignKey("OpenSourceInitiative.LicenseApi.Models.OsiLicense", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenSourceInitiative.LicenseApi.Models.OsiLicenseLinks", "Links", b1 =>
                        {
                            b1.Property<string>("OsiLicenseId")
                                .HasColumnType("TEXT");

                            b1.HasKey("OsiLicenseId");

                            b1.ToTable("OsiLicense");

                            b1.WithOwner()
                                .HasForeignKey("OsiLicenseId");

                            b1.OwnsOne("OpenSourceInitiative.LicenseApi.Models.OsiHref", "Collection", b2 =>
                                {
                                    b2.Property<string>("OsiLicenseLinksOsiLicenseId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Href")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasJsonPropertyName("href");

                                    b2.HasKey("OsiLicenseLinksOsiLicenseId");

                                    b2.ToTable("OsiLicense");

                                    b2.WithOwner()
                                        .HasForeignKey("OsiLicenseLinksOsiLicenseId");
                                });

                            b1.OwnsOne("OpenSourceInitiative.LicenseApi.Models.OsiHref", "Html", b2 =>
                                {
                                    b2.Property<string>("OsiLicenseLinksOsiLicenseId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Href")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasJsonPropertyName("href");

                                    b2.HasKey("OsiLicenseLinksOsiLicenseId");

                                    b2.ToTable("OsiLicense");

                                    b2.WithOwner()
                                        .HasForeignKey("OsiLicenseLinksOsiLicenseId");
                                });

                            b1.OwnsOne("OpenSourceInitiative.LicenseApi.Models.OsiHref", "Self", b2 =>
                                {
                                    b2.Property<string>("OsiLicenseLinksOsiLicenseId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Href")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasJsonPropertyName("href");

                                    b2.HasKey("OsiLicenseLinksOsiLicenseId");

                                    b2.ToTable("OsiLicense");

                                    b2.WithOwner()
                                        .HasForeignKey("OsiLicenseLinksOsiLicenseId");
                                });

                            b1.Navigation("Collection")
                                .IsRequired();

                            b1.Navigation("Html")
                                .IsRequired();

                            b1.Navigation("Self")
                                .IsRequired();
                        });

                    b.Navigation("Links")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
