name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'aur/**'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
