name: Reusable – Winget Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      WINGET_TOKEN:
        required: true
jobs:
  winget:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: frequency403.LicenseMeGui
          version: ${{ inputs.version }}
          release-tag: gui/v${{ inputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
