name: Reusable – Build

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      rid:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Publish
        run: >
          dotnet publish ${{ inputs.project }}
          --configuration Release
          --runtime ${{ inputs.rid }}
          --self-contained true
          -p:PublishSingleFile=true
          -p:DebugType=none
          -p:IncludeNativeLibrariesForSelfExtract=true
          --output ./publish/${{ inputs.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
          path: ./publish/${{ inputs.rid }}/
          retention-days: 7
